apiVersion: v1
kind: ConfigMap
metadata:
  name: shadowaudit-config
  namespace: vulnwatch
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: shadowaudit
  REDIS_URL: redis://redis:6379
  NODE_ENV: production
  PORT: "3000"
